package bryanthedragon.morph.cobblemonmorph.dependency.cobblemon.common.api.pokemon.labels

public object CobblemonPokemonLabels {
   public const val BABY: String = "baby"
   public const val CUSTOM: String = "custom"
   public const val CUSTOMIZED_OFFICIAL: String = "customized_official"
   public const val GENERATION_1: String = "gen1"
   public const val GENERATION_2: String = "gen2"
   public const val GENERATION_3: String = "gen3"
   public const val GENERATION_4: String = "gen4"
   public const val GENERATION_5: String = "gen5"
   public const val GENERATION_6: String = "gen6"
   public const val GENERATION_7: String = "gen7"
   public const val GENERATION_8: String = "gen8"
   public const val GENERATION_9: String = "gen9"
   public const val GMAX: String = "gmax"
   public const val LEGENDARY: String = "legendary"
   public const val MEGA: String = "mega"
   public const val MYTHICAL: String = "mythical"
   public const val PARADOX: String = "paradox"
   public const val PRIMAL: String = "primal"
   public const val PSEUDO_LEGENDARY: String = "pseudo_legendary"
   public const val REGIONAL: String = "regional"
   public const val REGIONAL_OF_ALOLA: String = "alola_regional"
   public const val REGIONAL_OF_GALAR: String = "galar_regional"
   public const val REGIONAL_OF_HISUI: String = "hisui_regional"
   public const val REGIONAL_OF_HOENN: String = "hoenn_regional"
   public const val REGIONAL_OF_JOHTO: String = "johto_regional"
   public const val REGIONAL_OF_KALOS: String = "kalos_regional"
   public const val REGIONAL_OF_KANTO: String = "kanto_regional"
   public const val REGIONAL_OF_PALDEA: String = "paldea_regional"
   public const val REGIONAL_OF_SINNOH: String = "sinnoh_regional"
   public const val REGIONAL_OF_UNOVA: String = "unova_regional"
   public const val TOTEM: String = "totem"
   public const val ULTRA_BEAST: String = "ultra_beast"
}
